# Vanta Linux - Live environment boot entry
title   Vanta Linux Live
linux   /%INSTALL_DIR%/boot/vmlinuz-linux
initrd  /%INSTALL_DIR%/boot/amd-ucode.img
initrd  /%INSTALL_DIR%/boot/initramfs-linux.img
options archisobasedir=%INSTALL_DIR% archisolabel=VANTA_LIVE loglevel=7 rd.debug rw nvidia-drm.modeset=1 nvidia-drm.fbdev=1
