# Vanta Linux - Live environment boot entry
title   Vanta Linux Live
linux   /%INSTALL_DIR%/boot/vmlinuz-linux
initrd  /%INSTALL_DIR%/boot/amd-ucode.img
initrd  /%INSTALL_DIR%/boot/initramfs-linux.img
options archisobasedir=%INSTALL_DIR% archisodevice=/dev/disk/by-label/VANTA_$(date +%Y%m) quiet splash nvidia-drm.modeset=1 nvidia-drm.fbdev=1
