# Vanta Linux - Live environment (NVIDIA safe mode, no modeset)
title   Vanta Linux Live (NVIDIA Safe)
linux   /%INSTALL_DIR%/boot/vmlinuz-linux
initrd  /%INSTALL_DIR%/boot/amd-ucode.img
initrd  /%INSTALL_DIR%/boot/initramfs-linux.img
options archisobasedir=%INSTALL_DIR% quiet splash nomodeset nvidia-drm.modeset=0
