# Vanta Linux Calamares installer configuration
modules-search: [ "/usr/lib/calamares/modules" ]

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - luksopenswaphookcfg
  - dracut
  - plymouthcfg
  - grubcfg
  - bootloader
  - vanta-settings
  - vanta-users
  - vanta-systemd
  - networkcfg
  - hwclock
  - services-systemd
  - grubcfg
  - bootloader
  - removeuser
  - umount

branding: vanta

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
presets:
  - /etc/calamares/presets.conf
