[Autologin]
Relogin=false
Session=plasmawayland

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot
Numlock=on

[Theme]
Current=vanta
CursorTheme=Vanta
Font=Inter,12
DisableAvatarsThreshold=5
EnableAvatars=true
ScreenScaleMethod=fit

[Users]
DefaultPath=/usr/local/bin:/usr/bin:/bin
HideShells=/sbin:/usr/sbin:/bin/nologin:/usr/bin/nologin
HideUsers=bin:daemon:adm:lp:sync:shutdown:halt:mail:news:uucp:operator:nobody:dbus:polkitd:rpc:rpcuser
MaximumUid=65000
MinimumUid=1000

[Wayland]
EnableHiDPI=true
SessionDir=/usr/share/wayland-sessions
